version: 2
jobs:
  build:
    docker:
      - image: circleci/jdk8:0.1.1

    working_directory: ~/repo

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      - restore_cache:
          keys:
          - cam-prometheus-demo-{{ checksum "pom.xml" }}
          - cam-prometheus-demo-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: cam-prometheus-demo-{{ checksum "pom.xml" }}

      - run: mvn integration-test